#!/bin/sh

CURRENT_WALLPAPER="$(cat "$HOME/.config/i3/current/wallpaper")"
RICE_DIR="$HOME/.config/i3/walls/"
mapfile -t WALLPAPERS < <(dir -1 "$RICE_DIR")

function reload_and_save() {
	NAME_FILE="$HOME/.config/i3/current/wallpaper"
	if [[ ! -f "$NAME_FILE" ]]; then
		touch "$NAME_FILE"
	fi

	echo "$NEXT_ELEMENT" > $NAME_FILE
}

function apply_wall() {
    wal -i $RICE_DIR/$NEXT_ELEMENT
}

function select_wall() {
    # Find the INDEX of the search string in the array
    local INDEX=-1
    local MODE=$1
    for ((i=0; i<${#WALLPAPERS[@]}; i++)); do
        if [ "${WALLPAPERS[i]}" == "$CURRENT_WALLPAPER" ]; then
            INDEX=$i
            echo "${WALLPAPERS[i]}"
            break
        fi
    done

    if [ "$INDEX" -ge 0 ]; then
        case "$MODE" in 
            -n)
                NEXT_INDEX=$(( (INDEX + 1) % ${#WALLPAPERS[@]} ))
                NEXT_ELEMENT="${WALLPAPERS[NEXT_INDEX]}"
                ;;
            -p)
                NEXT_INDEX=$(( (INDEX - 1 + ${#WALLPAPERS[@]}) % ${#WALLPAPERS[@]} ))
                NEXT_ELEMENT="${WALLPAPERS[NEXT_INDEX]}"
                ;;
        esac
    fi
}

function main() {
    case "$1" in
        -n)
            TRANSITION="grow"
            select_wall "$1"
            ;;
        -p)
            TRANSITION="outer"
            select_wall "$1"
            ;;
        *)
            echo "Invalid option: $1"
            exit 1
            ;;
    esac

    get_resolution
    apply_wall
    reload_and_save
}

main "$1"
